name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
  
env:
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EMAIL: ${{ secrets.EMAIL }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v4

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1

    # - name: Terraform Init
    #   run: terraform init

    # - name: Terraform Format
    #   run: terraform fmt 

    # - name: Terraform Plan
    #   run: terraform plan -out=plan.tfplan

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform apply -auto-approve "plan.tfplan"  

    - name: Terraform Destroy
      run: terraform destroy

    - name: Notify Plan Failure
      if: failure()
      run: |
        echo -e "Terraform Plan Failed\n\nTerraform Plan failed" 

    - name: Notify Apply Failure
      if: failure()
      run: |
        echo -e "Terraform Apply Failed\n\nTerraform Apply failed"

    - name: Notify Success
      if: success()
      run: |
        echo -e "Terraform Apply Succeeded\n\nTerraform Apply succeeded"
