name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
  
env:
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EMAIL: ${{ secrets.EMAIL }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install mailx
      run: sudo apt-get install -y mailutils

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt 

    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve "plan.tfplan"  

    - name: Notify Plan Failure
      if: failure()
      run: |
        echo "Terraform Plan failed" | mail -s "Terraform Plan Failed" ${{ secrets.EMAIL }}

    - name: Notify Apply Failure
      if: failure()
      run: |
        echo "Terraform Apply failed" | mail -s "Terraform Apply Failed" ${{ secrets.EMAIL }}

    - name: Notify Success
      if: success()
      run: |
        echo "Terraform Apply succeeded" | mail -s "Terraform Apply Succeeded" ${{ secrets.EMAIL }}
